<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>EasyProxy</AssemblyName>
    <RootNamespace>AppProxyHelper</RootNamespace>
    <Product>EasyProxy</Product>
    <Title>EasyProxy</Title>
    <Version>1.1.1</Version>
    <ApplicationIcon>Assets\EasyProxyAppIcon.ico</ApplicationIcon>
  </PropertyGroup>

</Project>
